//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ski_Service_Applikation
{
    using System;
    using System.Collections.Generic;
    
    public partial class alle_angebote_view
    {
        public double Preis { get; set; }
        public string Kategorie { get; set; }
        public string Marke { get; set; }
    }
}
