//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ski_Service_Applikation
{
    using System;
    using System.Collections.Generic;
    
    public partial class altersgruppe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public altersgruppe()
        {
            this.miete = new HashSet<miete>();
        }
    
        public int Altersgruppe_ID { get; set; }
        public string Altersgruppe1 { get; set; }
        public double Preismultiplikator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<miete> miete { get; set; }
    }
}
