//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ski_Service_Applikation
{
    using System;
    using System.Collections.Generic;
    
    public partial class angebot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public angebot()
        {
            this.miete = new HashSet<miete>();
        }
    
        public int Angebot_ID { get; set; }
        public double Preis_pro_Tag { get; set; }
        public int Kategorie_ID { get; set; }
        public int Marke_ID { get; set; }
    
        public virtual kategorie kategorie { get; set; }
        public virtual marke marke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<miete> miete { get; set; }
    }
}
