//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ski_Service_Applikation
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_miete_view
    {
        public int Miete_ID { get; set; }
        public int Angebot_ID { get; set; }
        public int Kunde_ID { get; set; }
        public System.DateTime Miet_Datum { get; set; }
        public System.DateTime Rueckgabe_Datum { get; set; }
        public int Menge { get; set; }
        public int Koerpergroesse { get; set; }
        public int Altersgruppe_ID { get; set; }
        public int Geschlecht_ID { get; set; }
        public int Status_ID { get; set; }
        public string concat_K_Nachname_______K_Vorname_ { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Kategorie { get; set; }
        public string Marke { get; set; }
        public string Status { get; set; }
        public double Preis { get; set; }
    }
}
